// GET ALL POSTS FROM FOLLOWING USERS
export const GET_ALL_FOLLOWING_USERS_POSTS = "GET_ALL_FOLLOWING_USERS_POSTS";
export const GET_ALL_FOLLOWING_USERS_POSTS_SUCCESS =
  "GET_ALL_FOLLOWING_USERS_POSTS_SUCCESS";

//GET USER POFILE DATA
export const GET_USER_PROFILE_DATA = "GET_USER_PROFILE_DATA";
export const GET_USER_PROFILE_DATA_SUCCESS = "GET_USER_PROFILE_DATA_SUCCESS";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const DELETE_USER_POST = "DELETE_USER_POST";

// GET ALL MESSAGES FROM USERS
export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES";
export const GET_ALL_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS";
export const POST_MESSAGE = "POST_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";

//EXPLORE SECTION POST
export const GET_ALL_POST = "GET_ALL_POST";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
